import * as cdk from 'aws-cdk-lib';
import { Template } from 'aws-cdk-lib/assertions';
import { TapStack } from '../lib/tap-stack';

// No nested stacks to mock in this simplified version

const environmentSuffix = process.env.ENVIRONMENT_SUFFIX || 'dev';

describe('TapStack', () => {
  let app: cdk.App;
  let stack: TapStack;
  let template: Template;

  beforeEach(() => {
    // Reset mocks before each test
    jest.clearAllMocks();

    app = new cdk.App();
    stack = new TapStack(app, 'TestTapStack', { 
      environmentSuffix,
      env: {
        account: '123456789012',
        region: 'us-east-1'
      }
    });
    template = Template.fromStack(stack);
  });

  describe('Stack Creation', () => {
    test('should create the stack successfully', () => {
      expect(stack).toBeDefined();
      expect(template).toBeDefined();
    });

    test('should have the correct stack name', () => {
      expect(stack.stackName).toBe('TestTapStack');
    });
  });

  describe('S3 Artifacts Bucket', () => {
    test('should create S3 bucket for pipeline artifacts', () => {
      template.hasResourceProperties('AWS::S3::Bucket', {
        BucketEncryption: {
          ServerSideEncryptionConfiguration: [
            {
              ServerSideEncryptionByDefault: {
                SSEAlgorithm: 'AES256'
              }
            }
          ]
        },
        PublicAccessBlockConfiguration: {
          BlockPublicAcls: true,
          BlockPublicPolicy: true,
          IgnorePublicAcls: true,
          RestrictPublicBuckets: true
        },
        VersioningConfiguration: {
          Status: 'Enabled'
        }
      });
    });

    test('should have auto-generated bucket name (not hardcoded)', () => {
      // Verify that the bucket name is auto-generated by CDK
      // The bucket should NOT have a hardcoded bucketName property
      const bucketResources = template.findResources('AWS::S3::Bucket');
      const pipelineBucket = Object.values(bucketResources).find(
        (resource: any) => resource.LogicalId === 'PipelineArtifactsBucketC4BB9BE3'
      );
      
      // The bucket should not have a hardcoded bucketName property
      expect(pipelineBucket?.Properties?.BucketName).toBeUndefined();
    });

    test('should have lifecycle rules for artifact cleanup', () => {
      template.hasResourceProperties('AWS::S3::Bucket', {
        LifecycleConfiguration: {
          Rules: [
            {
              Id: 'DeleteOldArtifacts',
              Status: 'Enabled',
              ExpirationInDays: 30,
              NoncurrentVersionExpiration: {
                NoncurrentDays: 7
              }
            }
          ]
        }
      });
    });

    test('should have bucket name output that references auto-generated name', () => {
      template.hasOutput('ArtifactsBucketName', {
        Description: 'Name of the S3 bucket storing pipeline artifacts'
      });
      
      // Verify the output references the bucket resource
      const outputs = template.findOutputs('ArtifactsBucketName');
      expect(outputs).toBeDefined();
    });
  });

  describe('CodePipeline', () => {
    test('should create CodePipeline with correct stages', () => {
      template.hasResourceProperties('AWS::CodePipeline::Pipeline', {
        Stages: [
          {
            Name: 'Source',
            Actions: [
              {
                Name: 'GitHub_Source',
                ActionTypeId: {
                  Category: 'Source',
                  Owner: 'ThirdParty',
                  Provider: 'GitHub'
                }
              }
            ]
          },
          {
            Name: 'Build',
            Actions: [
              {
                Name: 'Build_Application',
                ActionTypeId: {
                  Category: 'Build',
                  Owner: 'AWS',
                  Provider: 'CodeBuild'
                }
              }
            ]
          },
          {
            Name: 'PreDeploymentValidation',
            Actions: [
              {
                Name: 'Custom_Validation',
                ActionTypeId: {
                  Category: 'Invoke',
                  Owner: 'AWS',
                  Provider: 'Lambda'
                }
              }
            ]
          },
          {
            Name: 'ManualApproval',
            Actions: [
              {
                Name: 'Manual_Approval_For_Production',
                ActionTypeId: {
                  Category: 'Approval',
                  Owner: 'AWS',
                  Provider: 'Manual'
                }
              }
            ]
          },
          {
            Name: 'Deploy',
            Actions: [
              {
                Name: 'Deploy_To_Production',
                ActionTypeId: {
                  Category: 'Deploy',
                  Owner: 'AWS',
                  Provider: 'CodeDeploy'
                }
              }
            ]
          },
          {
            Name: 'PostDeploymentValidation',
            Actions: [
              {
                Name: 'Post_Deployment_Tests',
                ActionTypeId: {
                  Category: 'Invoke',
                  Owner: 'AWS',
                  Provider: 'Lambda'
                }
              }
            ]
          }
        ]
      });
    });
  });

  describe('CodeBuild Project', () => {
    test('should create CodeBuild project with correct configuration', () => {
      template.hasResourceProperties('AWS::CodeBuild::Project', {
        Name: 'enterprise-web-app-build',
        Environment: {
          Type: 'LINUX_CONTAINER',
          ComputeType: 'BUILD_GENERAL1_MEDIUM',
          Image: 'aws/codebuild/standard:5.0'
        },
        Artifacts: {
          Type: 'S3'
        }
      });
    });
  });

  describe('CodeDeploy Application', () => {
    test('should create CodeDeploy application', () => {
      template.hasResourceProperties('AWS::CodeDeploy::Application', {
        ApplicationName: 'enterprise-web-app'
      });
    });

    test('should create CodeDeploy deployment group', () => {
      template.hasResourceProperties('AWS::CodeDeploy::DeploymentGroup', {
        DeploymentGroupName: 'production-deployment-group',
        DeploymentConfigName: 'CodeDeployDefault.AllAtOnce',
        AutoRollbackConfiguration: {
          Enabled: true,
          Events: ['DEPLOYMENT_FAILURE', 'DEPLOYMENT_STOP_ON_REQUEST']
        }
      });
    });
  });

  describe('Lambda Function', () => {
    test('should create Lambda function for validation', () => {
      template.hasResourceProperties('AWS::Lambda::Function', {
        Runtime: 'nodejs18.x',
        Handler: 'pre-deployment-validation.handler',
        Timeout: 300,
        Environment: {
          Variables: {
            PIPELINE_NAME: 'enterprise-web-app-pipeline'
          }
        }
      });
    });

    test('should have proper IAM role for Lambda', () => {
      template.hasResourceProperties('AWS::IAM::Role', {
        AssumeRolePolicyDocument: {
          Statement: [
            {
              Action: 'sts:AssumeRole',
              Effect: 'Allow',
              Principal: {
                Service: 'lambda.amazonaws.com'
              }
            }
          ]
        }
      });
    });
  });

  describe('SNS Topic', () => {
    test('should create SNS topic for notifications', () => {
      template.hasResourceProperties('AWS::SNS::Topic', {
        TopicName: 'enterprise-cicd-notifications',
        DisplayName: 'Enterprise CI/CD Pipeline Notifications'
      });
    });

    test('should have email subscription', () => {
      template.hasResourceProperties('AWS::SNS::Subscription', {
        Protocol: 'email',
        Endpoint: 'devops@company.com'
      });
    });
  });

  describe('Auto Scaling Group', () => {
    test('should create Auto Scaling Group', () => {
      template.hasResourceProperties('AWS::AutoScaling::AutoScalingGroup', {
        MinSize: '2',
        MaxSize: '6',
        DesiredCapacity: '2'
      });
    });

    test('should use correct instance type', () => {
      template.hasResourceProperties('AWS::EC2::LaunchTemplate', {
        LaunchTemplateData: {
          InstanceType: 't3.micro'
        }
      });
    });
  });

  describe('IAM Roles', () => {
    test('should create CodePipeline service role', () => {
      template.hasResourceProperties('AWS::IAM::Role', {
        AssumeRolePolicyDocument: {
          Statement: [
            {
              Action: 'sts:AssumeRole',
              Effect: 'Allow',
              Principal: {
                Service: 'codepipeline.amazonaws.com'
              }
            }
          ]
        }
      });
    });

    test('should create CodeBuild service role', () => {
      template.hasResourceProperties('AWS::IAM::Role', {
        AssumeRolePolicyDocument: {
          Statement: [
            {
              Action: 'sts:AssumeRole',
              Effect: 'Allow',
              Principal: {
                Service: 'codebuild.amazonaws.com'
              }
            }
          ]
        }
      });
    });
  });

  describe('Parameter Store', () => {
    test('should create SSM parameters', () => {
      template.hasResourceProperties('AWS::SSM::Parameter', {
        Name: '/cicd/app-name',
        Type: 'String',
        Value: 'enterprise-web-app'
      });

      template.hasResourceProperties('AWS::SSM::Parameter', {
        Name: '/cicd/deployment-regions',
        Type: 'StringList',
        Value: 'us-east-1,us-west-2,eu-west-1'
      });

      template.hasResourceProperties('AWS::SSM::Parameter', {
        Name: '/cicd/notification-email',
        Type: 'String',
        Value: 'devops@company.com'
      });
    });
  });

  describe('CloudWatch Events', () => {
    test('should create CloudWatch Events rules for pipeline notifications', () => {
      template.hasResourceProperties('AWS::Events::Rule', {
        Description: 'Capture pipeline state changes',
        EventPattern: {
          source: ['aws.codepipeline'],
          'detail-type': ['CodePipeline Pipeline Execution State Change']
        }
      });

      template.hasResourceProperties('AWS::Events::Rule', {
        Description: 'Capture pipeline stage state changes',
        EventPattern: {
          source: ['aws.codepipeline'],
          'detail-type': ['CodePipeline Stage Execution State Change']
        }
      });
    });
  });

  describe('Stack Outputs', () => {
    test('should have required stack outputs', () => {
      template.hasOutput('PipelineName', {
        Description: 'Name of the CI/CD Pipeline'
      });

      template.hasOutput('PipelineUrl', {
        Description: 'URL to view the pipeline in AWS Console'
      });

      template.hasOutput('ArtifactsBucketName', {
        Description: 'Name of the S3 bucket storing pipeline artifacts'
      });

      template.hasOutput('NotificationsTopicArn', {
        Description: 'ARN of the SNS topic for pipeline notifications'
      });

      template.hasOutput('CodeDeployApplicationName', {
        Description: 'Name of the CodeDeploy application'
      });

      template.hasOutput('BuildProjectName', {
        Description: 'Name of the CodeBuild project'
      });
    });
  });
});
