import fs from 'fs';
import path from 'path';

describe('TapStack CloudFormation Template', () => {
  let template: any;

  beforeAll(() => {
    // Use the JSON version generated by cfn-flip for unit tests
    // This avoids YAML parsing issues with CloudFormation intrinsic functions
    const templatePath = path.join(__dirname, '../lib/TapStack.json');
    const templateContent = fs.readFileSync(templatePath, 'utf8');
    template = JSON.parse(templateContent);
  });

  describe('Template Structure', () => {
    test('should have valid CloudFormation format version', () => {
      expect(template.AWSTemplateFormatVersion).toBe('2010-09-09');
    });

    test('should have a description', () => {
      expect(template.Description).toBeDefined();
      expect(template.Description).toBe(
        'Multi-region deployable CloudFormation template with comprehensive AWS services'
      );
    });

    test('should have all required sections', () => {
      expect(template.Parameters).toBeDefined();
      expect(template.Mappings).toBeDefined();
      expect(template.Conditions).toBeDefined();
      expect(template.Resources).toBeDefined();
      expect(template.Outputs).toBeDefined();
    });
  });

  describe('Parameters', () => {
    test('should have EnvironmentSuffix parameter', () => {
      expect(template.Parameters.EnvironmentSuffix).toBeDefined();
      const envParam = template.Parameters.EnvironmentSuffix;
      expect(envParam.Type).toBe('String');
      expect(envParam.Default).toBe('dev');
      // No AllowedValues constraint - accepts any string
      expect(envParam.AllowedValues).toBeUndefined();
    });

    test('should have VpcCidr parameter', () => {
      expect(template.Parameters.VpcCidr).toBeDefined();
      const vpcParam = template.Parameters.VpcCidr;
      expect(vpcParam.Type).toBe('String');
      expect(vpcParam.Default).toBe('10.0.0.0/16');
    });

    test('should have CrossRegionReplicationBuckets parameter', () => {
      expect(template.Parameters.CrossRegionReplicationBuckets).toBeDefined();
      const replicationParam = template.Parameters.CrossRegionReplicationBuckets;
      expect(replicationParam.Type).toBe('CommaDelimitedList');
      expect(replicationParam.Default).toBe('');
    });

    test('should have RandomSuffix parameter', () => {
      expect(template.Parameters.RandomSuffix).toBeDefined();
      const suffixParam = template.Parameters.RandomSuffix;
      expect(suffixParam.Type).toBe('String');
      expect(suffixParam.Default).toBe('12345');
      expect(suffixParam.AllowedPattern).toBe('[0-9]{5}');
    });

    test('should have RDS parameters', () => {
      expect(template.Parameters.DBInstanceClass).toBeDefined();
      expect(template.Parameters.DBName).toBeDefined();
      expect(template.Parameters.DBBackupRetentionPeriod).toBeDefined();

      const dbBackupParam = template.Parameters.DBBackupRetentionPeriod;
      expect(dbBackupParam.MinValue).toBe(7);
      expect(dbBackupParam.Default).toBe(7);
    });

    test('should have WAFScope parameter', () => {
      expect(template.Parameters.WAFScope).toBeDefined();
      const wafParam = template.Parameters.WAFScope;
      expect(wafParam.AllowedValues).toContain('REGIONAL');
      expect(wafParam.AllowedValues).toContain('CLOUDFRONT');
      expect(wafParam.Default).toBe('REGIONAL');
    });
  });

  describe('Conditions', () => {
    test('should have HasReplicationBuckets condition', () => {
      expect(template.Conditions).toBeDefined();
      expect(template.Conditions.HasReplicationBuckets).toBeDefined();
    });
  });

  describe('Mappings', () => {
    test('should have RegionMap mapping', () => {
      expect(template.Mappings).toBeDefined();
      expect(template.Mappings.RegionMap).toBeDefined();

      // Test a few regions
      expect(template.Mappings.RegionMap['us-east-1']).toBeDefined();
      expect(template.Mappings.RegionMap['us-west-2']).toBeDefined();
      expect(template.Mappings.RegionMap['eu-west-1']).toBeDefined();

      // Test CIDR structure
      const usEast1 = template.Mappings.RegionMap['us-east-1'];
      expect(usEast1.PublicSubnet1CIDR).toBeDefined();
      expect(usEast1.PublicSubnet2CIDR).toBeDefined();
      expect(usEast1.PrivateSubnet1CIDR).toBeDefined();
      expect(usEast1.PrivateSubnet2CIDR).toBeDefined();
    });
  });

  describe('Resources', () => {
    // VPC Resources
    test('should have VPC infrastructure resources', () => {
      expect(template.Resources.VPC).toBeDefined();
      expect(template.Resources.VPC.Type).toBe('AWS::EC2::VPC');

      expect(template.Resources.InternetGateway).toBeDefined();
      expect(template.Resources.PublicSubnet1).toBeDefined();
      expect(template.Resources.PublicSubnet2).toBeDefined();
      expect(template.Resources.PrivateSubnet1).toBeDefined();
      expect(template.Resources.PrivateSubnet2).toBeDefined();

      expect(template.Resources.NatGateway1).toBeDefined();
      expect(template.Resources.NatGateway2).toBeDefined();
    });

    // S3 Resources
    test('should have S3 resources', () => {
      expect(template.Resources.S3Bucket).toBeDefined();
      expect(template.Resources.S3Bucket.Type).toBe('AWS::S3::Bucket');

      expect(template.Resources.S3BucketKMSKey).toBeDefined();
      expect(template.Resources.S3BucketKMSKey.Type).toBe('AWS::KMS::Key');

      expect(template.Resources.S3ReplicationRole).toBeDefined();
      expect(template.Resources.S3ReplicationRole.Type).toBe('AWS::IAM::Role');
    });

    // RDS Resources
    test('should have RDS resources', () => {
      expect(template.Resources.DbInstance).toBeDefined();
      expect(template.Resources.DbInstance.Type).toBe('AWS::RDS::DBInstance');

      expect(template.Resources.DbSubnetGroup).toBeDefined();
      expect(template.Resources.DbParameterGroup).toBeDefined();
      expect(template.Resources.DbSecret).toBeDefined();
      expect(template.Resources.DbSecurityGroup).toBeDefined();
    });

    // Lambda Resources
    test('should have Lambda resources', () => {
      expect(template.Resources.WebAppLambda).toBeDefined();
      expect(template.Resources.WebAppLambda.Type).toBe('AWS::Lambda::Function');

      expect(template.Resources.SecretRotationLambda).toBeDefined();
      expect(template.Resources.SecretRotationLambda.Type).toBe('AWS::Lambda::Function');
    });

    // Load Balancer Resources
    test('should have Load Balancer resources', () => {
      expect(template.Resources.ALB).toBeDefined();
      expect(template.Resources.ALB.Type).toBe('AWS::ElasticLoadBalancingV2::LoadBalancer');

      expect(template.Resources.ALBListener).toBeDefined();
      expect(template.Resources.ALBTargetGroup).toBeDefined();
    });

    // Auto Scaling Resources
    test('should have Auto Scaling resources', () => {
      expect(template.Resources.AutoScalingGroup).toBeDefined();
      expect(template.Resources.AutoScalingGroup.Type).toBe('AWS::AutoScaling::AutoScalingGroup');

      expect(template.Resources.LaunchTemplate).toBeDefined();
      expect(template.Resources.ScaleOutPolicy).toBeDefined();
    });

    // API Gateway Resources
    test('should have API Gateway resources', () => {
      expect(template.Resources.ApiGateway).toBeDefined();
      expect(template.Resources.ApiGateway.Type).toBe('AWS::ApiGateway::RestApi');

      expect(template.Resources.ApiGatewayRootMethod).toBeDefined();
      expect(template.Resources.ApiGatewayDeployment).toBeDefined();
      expect(template.Resources.ApiGatewayStage).toBeDefined();
    });

    // Monitoring Resources
    test('should have monitoring and logging resources', () => {
      expect(template.Resources.CloudTrail).toBeDefined();
      expect(template.Resources.CloudTrail.Type).toBe('AWS::CloudTrail::Trail');

      expect(template.Resources.ConfigRecorder).toBeDefined();
      expect(template.Resources.ConfigRecorder.Type).toBe('AWS::Config::ConfigurationRecorder');

      expect(template.Resources.WebACL).toBeDefined();
      expect(template.Resources.WebACL.Type).toBe('AWS::WAFv2::WebACL');
    });
  });

  describe('Outputs', () => {
    test('should have key infrastructure outputs', () => {
      const expectedOutputs = [
        'S3BucketName',
        'S3BucketArn',
        'VpcId',
        'LoadBalancerDnsName',
        'DbInstanceEndpoint',
        'WebsiteUrl',
        'ApiUrl',
        'WebACLArn'
      ];

      expectedOutputs.forEach(outputName => {
        expect(template.Outputs[outputName]).toBeDefined();
      });
    });

    test('should have S3 related outputs', () => {
      expect(template.Outputs.S3BucketName).toBeDefined();
      expect(template.Outputs.S3BucketArn).toBeDefined();
      expect(template.Outputs.S3ReplicationRoleArn).toBeDefined();
      expect(template.Outputs.S3BucketKMSKeyArn).toBeDefined();
    });

    test('should have VPC related outputs', () => {
      expect(template.Outputs.VpcId).toBeDefined();
      expect(template.Outputs.PublicSubnet1Id).toBeDefined();
      expect(template.Outputs.PublicSubnet2Id).toBeDefined();
      expect(template.Outputs.PrivateSubnet1Id).toBeDefined();
      expect(template.Outputs.PrivateSubnet2Id).toBeDefined();
    });

    test('should have application endpoints outputs', () => {
      const websiteOutput = template.Outputs.WebsiteUrl;
      expect(websiteOutput).toBeDefined();
      expect(websiteOutput.Description).toContain('website');

      const apiOutput = template.Outputs.ApiUrl;
      expect(apiOutput).toBeDefined();
      expect(apiOutput.Description).toContain('API');
    });

    test('outputs should have export names', () => {
      Object.keys(template.Outputs).forEach(outputKey => {
        const output = template.Outputs[outputKey];
        expect(output.Export).toBeDefined();
        expect(output.Export.Name).toBeDefined();
      });
    });
  });

  describe('Template Validation', () => {
    test('should have valid YAML structure', () => {
      expect(template).toBeDefined();
      expect(typeof template).toBe('object');
    });

    test('should not have any undefined or null required sections', () => {
      expect(template.AWSTemplateFormatVersion).not.toBeNull();
      expect(template.Description).not.toBeNull();
      expect(template.Parameters).not.toBeNull();
      expect(template.Resources).not.toBeNull();
      expect(template.Outputs).not.toBeNull();
    });

    test('should have substantial number of resources', () => {
      const resourceCount = Object.keys(template.Resources).length;
      expect(resourceCount).toBeGreaterThan(30); // We have many resources
    });

    test('should have multiple parameters', () => {
      const parameterCount = Object.keys(template.Parameters).length;
      expect(parameterCount).toBeGreaterThan(5);
    });

    test('should have multiple outputs', () => {
      const outputCount = Object.keys(template.Outputs).length;
      expect(outputCount).toBeGreaterThan(10);
    });
  });

  describe('Security and Best Practices', () => {
    test('RDS instance should not have deletion protection enabled', () => {
      const dbInstance = template.Resources.DbInstance;
      expect(dbInstance.Properties.DeletionProtection).toBe(false);
    });

    test('S3 buckets should have versioning enabled', () => {
      const s3Bucket = template.Resources.S3Bucket;
      expect(s3Bucket.Properties.VersioningConfiguration.Status).toBe('Enabled');
    });

    test('S3 buckets should have encryption configured', () => {
      const s3Bucket = template.Resources.S3Bucket;
      expect(s3Bucket.Properties.BucketEncryption).toBeDefined();
      expect(s3Bucket.Properties.BucketEncryption.ServerSideEncryptionConfiguration).toBeDefined();
    });

    test('Lambda functions should use supported runtime', () => {
      const webAppLambda = template.Resources.WebAppLambda;
      const rotationLambda = template.Resources.SecretRotationLambda;

      expect(webAppLambda.Properties.Runtime).toBe('python3.11');
      expect(rotationLambda.Properties.Runtime).toBe('python3.11');
    });

    test('RDS should use current MySQL version', () => {
      const dbInstance = template.Resources.DbInstance;
      expect(dbInstance.Properties.EngineVersion).toBe('8.0.43');
    });

    test('Auto Scaling Group should have reasonable max size', () => {
      const asg = template.Resources.AutoScalingGroup;
      expect(asg.Properties.MaxSize).toBeLessThanOrEqual(4);
    });

    test('S3 bucket names should include random suffix', () => {
      const s3Bucket = template.Resources.S3Bucket;
      const bucketName = s3Bucket.Properties.BucketName;
      expect(bucketName['Fn::Sub']).toContain('${RandomSuffix}');
    });
  });

  describe('Resource Dependencies', () => {
    test('ConfigRecorder should depend on ConfigDeliveryChannel', () => {
      const configRecorder = template.Resources.ConfigRecorder;
      expect(configRecorder.DependsOn).toBe('ConfigDeliveryChannel');
    });

    test('SecretRotationSchedule should reference SecretRotationLambda via GetAtt', () => {
      const rotationSchedule = template.Resources.SecretRotationSchedule;
      expect(rotationSchedule.Properties.RotationLambdaARN['Fn::GetAtt']).toEqual(['SecretRotationLambda', 'Arn']);
    });

    test('NAT Gateway EIPs should depend on InternetGatewayAttachment', () => {
      const natEip1 = template.Resources.NatGateway1EIP;
      const natEip2 = template.Resources.NatGateway2EIP;

      expect(natEip1.DependsOn).toBe('InternetGatewayAttachment');
      expect(natEip2.DependsOn).toBe('InternetGatewayAttachment');
    });
  });

  describe('Conditional Logic', () => {
    test('S3 replication should be conditional', () => {
      const s3Bucket = template.Resources.S3Bucket;
      const replicationConfig = s3Bucket.Properties.ReplicationConfiguration;

      expect(replicationConfig['Fn::If']).toBeDefined();
      expect(replicationConfig['Fn::If'][0]).toBe('HasReplicationBuckets');
    });
  });
});
