// tests/unit/terraform.unit.test.ts
// Unit tests for tfplan.json generated by Terraform plan
// No Terraform commands are executed here — assumes plan JSON already exists.

import fs from "fs";
import path from "path";

const OUTPUT_DIR = path.resolve(__dirname, "../tf-outputs");
const PLAN_JSON = path.join(OUTPUT_DIR, "tfplan.json");

function readPlan(): any {
  if (!fs.existsSync(PLAN_JSON)) {
    throw new Error(
      `[unit] Terraform plan JSON not found at: ${PLAN_JSON}\n` +
      `Run: npm run tf:plan-json before running unit tests.`
    );
  }
  try {
    return JSON.parse(fs.readFileSync(PLAN_JSON, "utf8"));
  } catch (err) {
    throw new Error(`[unit] Failed to parse tfplan.json: ${(err as Error).message}`);
  }
}

describe("Terraform plan.json structure", () => {
  test("plan.json exists and is valid JSON", () => {
    expect(fs.existsSync(PLAN_JSON)).toBe(true);
    expect(() => readPlan()).not.toThrow();
  });

  test("VPC should have correct CIDR", () => {
    const plan = readPlan();
    const vpc = plan.resource_changes.find(
      (r: any) => r.type === "aws_vpc" && r.name === "main"
    );
    expect(vpc).toBeDefined();
    expect(vpc.change.after.cidr_block).toBe("172.31.0.0/16");
  });

  test("Public subnet should have correct CIDR", () => {
    const plan = readPlan();
    const pubSubnet = plan.resource_changes.find(
      (r: any) => r.type === "aws_subnet" && r.name === "public"
    );
    expect(pubSubnet).toBeDefined();
    expect(pubSubnet.change.after.cidr_block).toBe("172.31.0.0/20");
  });

  test("Private subnet should have correct CIDR", () => {
    const plan = readPlan();
    const privSubnet = plan.resource_changes.find(
      (r: any) => r.type === "aws_subnet" && r.name === "private"
    );
    expect(privSubnet).toBeDefined();
    expect(privSubnet.change.after.cidr_block).toBe("172.31.16.0/20");
  });

  test("Bastion host should have IAM instance profile", () => {
    const plan = readPlan();
    const bastion = plan.resource_changes.find(
      (r: any) => r.type === "aws_instance" && r.name === "bastion"
    );
    expect(bastion).toBeDefined();
    expect(bastion.change.after.iam_instance_profile).toBeDefined();
  });

  test("Secrets Manager secret should exist", () => {
    const plan = readPlan();
    const secret = plan.resource_changes.find(
      (r: any) =>
        r.type === "aws_secretsmanager_secret" &&
        r.name === "app_secrets"
    );
    expect(secret).toBeDefined();
  });

  test("Plan does not contain hardcoded AWS credentials", () => {
    const planText = fs.readFileSync(PLAN_JSON, "utf8");
    expect(/aws_access_key_id\s*=/.test(planText)).toBe(false);
    expect(/aws_secret_access_key\s*=/.test(planText)).toBe(false);
  });
});
