from constructs import Construct
from cdktf_cdktf_provider_aws.rds_cluster import RdsCluster
from cdktf_cdktf_provider_aws.rds_cluster_instance import RdsClusterInstance
from cdktf_cdktf_provider_aws.db_subnet_group import DbSubnetGroup
from cdktf_cdktf_provider_aws.rds_cluster_parameter_group import RdsClusterParameterGroup, RdsClusterParameterGroupParameter
from cdktf_cdktf_provider_aws.db_parameter_group import DbParameterGroup, DbParameterGroupParameter


class DatabaseConstruct(Construct):
    def __init__(self, scope: Construct, id: str, environment_suffix: str, vpc, security):
        super().__init__(scope, id)

        # DB Subnet Group
        db_subnet_group = DbSubnetGroup(self, "db_subnet_group",
            name=f"financial-db-subnet-group-{environment_suffix}",
            subnet_ids=[subnet.id for subnet in vpc.private_subnets],
            tags={
                "Name": f"financial-db-subnet-group-{environment_suffix}",
                "Environment": f"{environment_suffix}",
                "Application": "financial-transaction-platform",
                "CostCenter": "engineering"
            }
        )

        # Cluster Parameter Group
        cluster_parameter_group = RdsClusterParameterGroup(self, "cluster_param_group",
            name=f"financial-aurora-cluster-pg-{environment_suffix}",
            family="aurora-mysql8.0",
            description="Aurora MySQL 8.0 cluster parameter group",
            parameter=[
                RdsClusterParameterGroupParameter(
                    name="character_set_server",
                    value="utf8mb4"
                ),
                RdsClusterParameterGroupParameter(
                    name="collation_server",
                    value="utf8mb4_unicode_ci"
                ),
                RdsClusterParameterGroupParameter(
                    name="require_secure_transport",
                    value="ON"
                )
            ],
            tags={
                "Name": f"financial-cluster-pg-{environment_suffix}",
                "Environment": f"{environment_suffix}",
                "Application": "financial-transaction-platform",
                "CostCenter": "engineering"
            }
        )

        # Instance Parameter Group
        instance_parameter_group = DbParameterGroup(self, "instance_param_group",
            name=f"financial-aurora-instance-pg-{environment_suffix}",
            family="aurora-mysql8.0",
            description="Aurora MySQL 8.0 instance parameter group",
            parameter=[
                DbParameterGroupParameter(
                    name="slow_query_log",
                    value="1"
                ),
                DbParameterGroupParameter(
                    name="long_query_time",
                    value="2"
                )
            ],
            tags={
                "Name": f"financial-instance-pg-{environment_suffix}",
                "Environment": f"{environment_suffix}",
                "Application": "financial-transaction-platform",
                "CostCenter": "engineering"
            }
        )

        # Aurora MySQL Cluster
        # Note: Master password is generated by Secrets Manager
        # The actual password injection happens in the SecretsConstruct
        import random
        import string

        # Generate a random password for the initial cluster creation
        # This will be immediately overridden by Secrets Manager
        def generate_password():
            chars = string.ascii_letters + string.digits + string.punctuation
            # Exclude problematic characters for RDS
            chars = ''.join(c for c in chars if c not in ["'", '"', '/', '\\', '@'])
            return ''.join(random.choice(chars) for _ in range(32))

        self.cluster = RdsCluster(self, "aurora_cluster",
            cluster_identifier=f"financial-aurora-{environment_suffix}",
            engine="aurora-mysql",
            engine_version="8.0.mysql_aurora.3.04.0",
            engine_mode="provisioned",
            database_name="financialdb",
            master_username="admin",
            master_password=generate_password(),  # Randomly generated, will be managed by Secrets Manager
            db_subnet_group_name=db_subnet_group.name,
            db_cluster_parameter_group_name=cluster_parameter_group.name,
            vpc_security_group_ids=[security.rds_sg.id],
            storage_encrypted=True,
            kms_key_id=security.kms_key.arn,
            backup_retention_period=7,
            preferred_backup_window="03:00-04:00",
            preferred_maintenance_window="mon:04:00-mon:05:00",
            enabled_cloudwatch_logs_exports=["audit", "error", "general", "slowquery"],
            deletion_protection=False,  # Set to False for test environments
            skip_final_snapshot=True,   # Set to True for test environments
            apply_immediately=True,
            tags={
                "Name": f"financial-aurora-{environment_suffix}",
                "Environment": f"{environment_suffix}",
                "Application": "financial-transaction-platform",
                "CostCenter": "engineering"
            }
        )

        # Aurora Cluster Instances (2 instances for HA)
        self.instances = []
        for i in range(2):
            instance = RdsClusterInstance(self, f"aurora_instance_{i}",
                identifier=f"financial-aurora-{environment_suffix}-{i+1}",
                cluster_identifier=self.cluster.id,
                instance_class="db.r6g.large",
                engine=self.cluster.engine,
                engine_version=self.cluster.engine_version,
                db_parameter_group_name=instance_parameter_group.name,
                publicly_accessible=False,
                performance_insights_enabled=True,
                performance_insights_kms_key_id=security.kms_key.arn,
                performance_insights_retention_period=7,
                monitoring_interval=0,  # Disabled - would need IAM role for enhanced monitoring
                tags={
                    "Name": f"financial-aurora-instance-{i+1}-{environment_suffix}",
                    "Environment": f"{environment_suffix}",
                    "Application": "financial-transaction-platform",
                    "CostCenter": "engineering"
                }
            )
            self.instances.append(instance)
