#!/bin/bash

echo "🔧 AWS Configuration Helper"
echo "================================"
echo ""
echo "To deploy the Terraform infrastructure, you need AWS credentials configured."
echo ""
echo "Choose one of these options:"
echo ""
echo "1. Configure AWS CLI with your credentials:"
echo "   aws configure"
echo "   (You'll need: Access Key ID, Secret Access Key, Region: us-west-2)"
echo ""
echo "2. Set environment variables:"
echo "   export AWS_ACCESS_KEY_ID='your_access_key'"
echo "   export AWS_SECRET_ACCESS_KEY='your_secret_key'"
echo "   export AWS_DEFAULT_REGION='us-west-2'"
echo ""
echo "3. Use AWS SSO (if configured):"
echo "   aws sso login"
echo ""
echo "After configuring credentials, run:"
echo "   npm run tf:plan     # Generate plan"
echo "   npm run tf:deploy   # Deploy infrastructure"
echo ""
echo "✅ Security Hub fix is already applied in monitoring.tf"
