# Shared metadata
output "environment_suffix" {
  description = "Environment suffix applied to all resource names for isolation."
  value       = var.environment_suffix
}

# Cluster Outputs
output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = aws_eks_cluster.main.endpoint
}

output "cluster_name" {
  description = "EKS cluster name"
  value       = aws_eks_cluster.main.name
}

output "cluster_certificate_authority_data" {
  description = "Base64 encoded certificate data required to communicate with the cluster"
  value       = aws_eks_cluster.main.certificate_authority[0].data
  sensitive   = true
}

output "cluster_oidc_issuer_url" {
  description = "The URL on the EKS cluster OIDC Issuer"
  value       = aws_eks_cluster.main.identity[0].oidc[0].issuer
}

output "cluster_version" {
  description = "The Kubernetes version for the cluster"
  value       = aws_eks_cluster.main.version
}

output "cluster_platform_version" {
  description = "The platform version for the cluster"
  value       = aws_eks_cluster.main.platform_version
}

output "cluster_status" {
  description = "Status of the EKS cluster. One of `CREATING`, `ACTIVE`, `DELETING`, `FAILED`"
  value       = aws_eks_cluster.main.status
}

output "cluster_security_group_id" {
  description = "Security group ID attached to the EKS control plane"
  value       = aws_security_group.eks_cluster.id
}

output "cluster_iam_role_arn" {
  description = "IAM role ARN assumed by the EKS control plane"
  value       = aws_iam_role.eks_cluster.arn
}

output "node_security_group_id" {
  description = "Security group ID attached to the EKS worker nodes"
  value       = aws_security_group.eks_nodes.id
}

output "node_groups" {
  description = "Node group details"
  value = {
    frontend = {
      id            = aws_eks_node_group.frontend.id
      arn           = aws_eks_node_group.frontend.arn
      status        = aws_eks_node_group.frontend.status
      capacity_type = aws_eks_node_group.frontend.capacity_type
    }
    backend = {
      id            = aws_eks_node_group.backend.id
      arn           = aws_eks_node_group.backend.arn
      status        = aws_eks_node_group.backend.status
      capacity_type = aws_eks_node_group.backend.capacity_type
    }
  }
}

output "frontend_node_group_name" {
  description = "Frontend node group identifier"
  value       = aws_eks_node_group.frontend.node_group_name
}

output "backend_node_group_name" {
  description = "Backend node group identifier"
  value       = aws_eks_node_group.backend.node_group_name
}

output "cluster_autoscaler_role_arn" {
  description = "ARN of IAM role for cluster autoscaler"
  value       = aws_iam_role.cluster_autoscaler.arn
}

output "app_irsa_role_arn" {
  description = "ARN of IAM role for application IRSA"
  value       = aws_iam_role.app_irsa.arn
}

# OIDC Provider Output
output "oidc_provider_arn" {
  description = "ARN of the OIDC Provider for EKS"
  value       = aws_iam_openid_connect_provider.eks.arn
}

# KMS Key Output
output "kms_key_arn" {
  description = "The Amazon Resource Name (ARN) of the KMS key"
  value       = aws_kms_key.eks.arn
}

# CloudWatch Log Group
output "cluster_log_group_name" {
  description = "Name of the CloudWatch log group for EKS cluster logs"
  value       = aws_cloudwatch_log_group.eks.name
}

# Kubernetes Configuration
output "kubectl_config" {
  description = "kubectl config as generated by the module"
  value = {
    cluster_name = aws_eks_cluster.main.name
    endpoint     = aws_eks_cluster.main.endpoint
    region       = var.aws_region
    ca_data      = aws_eks_cluster.main.certificate_authority[0].data
  }
  sensitive = true
}

output "kubernetes_namespace" {
  description = "Base Kubernetes namespace name (without environment suffix)."
  value       = var.kubernetes_namespace
}

output "payments_namespace" {
  description = "Kubernetes namespace that hosts the payments workloads."
  value       = var.manage_kubernetes_resources ? kubernetes_namespace.payments[0].metadata[0].name : null
}

output "payments_service_account" {
  description = "IRSA-enabled service account bound to the payments namespace."
  value       = var.manage_kubernetes_resources ? kubernetes_service_account.payments_app[0].metadata[0].name : null
}

output "alerts_topic_arn" {
  description = "SNS topic ARN used for autoscaler alerts."
  value       = aws_sns_topic.eks_alerts.arn
}

output "database_secret_name" {
  description = "Name of the database credentials secret consumed by workloads."
  value       = local.database_secret_name
}

output "frontend_service_name" {
  description = "ClusterIP service fronting the payments frontend workload."
  value       = var.manage_kubernetes_resources ? kubernetes_service.frontend[0].metadata[0].name : null
}

output "backend_service_name" {
  description = "ClusterIP service fronting the payments backend workload."
  value       = var.manage_kubernetes_resources ? kubernetes_service.backend[0].metadata[0].name : null
}
 