variable "aws_region" {
  description = "AWS region where the EKS infrastructure will be deployed."
  type        = string
  default     = "us-east-1"
}

variable "environment_suffix" {
  description = "Unique suffix appended to resource names and tags to ensure environment isolation."
  type        = string
  default     = "prod"
}

variable "cluster_name_prefix" {
  description = "Base name for the EKS cluster. The environment suffix is appended automatically."
  type        = string
  default     = "payments-platform-eks"
}

variable "cluster_version" {
  description = "Desired Kubernetes control plane version."
  type        = string
  default     = "1.29"
}

variable "cluster_log_retention_days" {
  description = "Retention period in days for EKS control plane CloudWatch Logs."
  type        = number
  default     = 30
}

variable "vpc_id_parameter_name" {
  description = "AWS Systems Manager Parameter Store name that holds the target VPC ID."
  type        = string
  default     = "/infrastructure/vpc/id"
}

variable "private_subnet_tag_key" {
  description = "Tag key used to identify private subnets."
  type        = string
  default     = "Type"
}

variable "private_subnet_tag_value" {
  description = "Tag value used to identify private subnets."
  type        = string
  default     = "private"
}

variable "availability_zones" {
  description = "Availability zones used for the EKS control plane and node groups."
  type        = list(string)
  default     = ["us-east-1a", "us-east-1b", "us-east-1c"]
}

variable "kubernetes_namespace" {
  description = "Namespace used for the payment services workloads."
  type        = string
  default     = "payments"
}

variable "database_secret_name" {
  description = "Name of the AWS Secrets Manager secret that stores the database credentials."
  type        = string
  default     = "payments/database"
}

variable "existing_vpc_id" {
  description = "Optional pre-existing VPC ID. If left blank, a new VPC will be created."
  type        = string
  default     = ""

  validation {
    condition = !(
      var.existing_vpc_id != "" &&
      (
        length(var.existing_private_subnet_ids) == 0 ||
        length(var.existing_public_subnet_ids) == 0
      )
    )
    error_message = "When providing existing_vpc_id you must also supply both existing_private_subnet_ids and existing_public_subnet_ids."
  }
}

variable "existing_private_subnet_ids" {
  description = "Optional list of private subnet IDs to use with the existing VPC."
  type        = list(string)
  default     = []
}

variable "existing_public_subnet_ids" {
  description = "Optional list of public subnet IDs to use with the existing VPC."
  type        = list(string)
  default     = []
}

variable "manage_vpc_ssm_parameter" {
  description = "Whether to manage the SSM parameter that stores the VPC ID."
  type        = bool
  default     = true
}

variable "existing_database_secret_arn" {
  description = "Optional ARN of a pre-existing database credential secret."
  type        = string
  default     = ""
}

variable "database_secret_string" {
  description = "JSON payload to store in the autogenerated database secret when no existing ARN is supplied."
  type        = string
  default     = <<EOT
{
  "username": "payments_app",
  "password": "ChangeMeNow123!"
}
EOT
}

variable "manage_kubernetes_resources" {
  description = "Whether to create Kubernetes resources (namespaces, service accounts, deployments). Set to false if Terraform runner cannot access the private EKS endpoint."
  type        = bool
  default     = false
}

variable "node_group_deployment_suffix" {
  description = "Optional suffix to append to node group names to avoid conflicts with failed node groups from previous deployments. Change this value to force new node groups."
  type        = string
  default     = "v5"
}

variable "resource_deployment_suffix" {
  description = "Optional suffix to append to resource names (IAM roles, CloudWatch log groups) to avoid conflicts with existing resources from previous deployments. Leave empty to use existing resources if they exist."
  type        = string
  default     = "v5"
}

locals {
  node_group_suffix        = "-${var.node_group_deployment_suffix}"
  resource_suffix          = "-${var.resource_deployment_suffix}"
  cluster_name             = "${var.cluster_name_prefix}-${var.environment_suffix}${local.resource_suffix}"
  frontend_node_group_name = "${local.cluster_name}-frontend${local.node_group_suffix}"
  backend_node_group_name  = "${local.cluster_name}-backend${local.node_group_suffix}"
  frontend_launch_template = "${local.cluster_name}-frontend-lt"
  backend_launch_template  = "${local.cluster_name}-backend-lt"
  kms_alias_name           = "alias/${local.cluster_name}${local.resource_suffix}"
  log_group_name           = "/aws/eks/${local.cluster_name}${local.resource_suffix}/cluster"
  eks_cluster_role_name    = "${local.cluster_name}-cluster-role${local.resource_suffix}"
  namespace_name           = "${var.kubernetes_namespace}-${var.environment_suffix}"
  database_secret_name     = "${var.database_secret_name}-${var.environment_suffix}${local.resource_suffix}"
  sns_topic_name           = "${local.cluster_name}-autoscaler-alerts${local.resource_suffix}"

  common_tags = {
    Environment       = "production"
    EnvironmentSuffix = var.environment_suffix
    ManagedBy         = "terraform"
    Application       = "payments-platform"
    Component         = "eks"
  }
}

