name: "Setup Environment"
description: "Sets up Node.js, Python and Terraform environment and restores build artifacts"
inputs:
  node-version:
    description: "Node.js version to use"
    required: true
    default: "22.17.0"
  download-artifacts:
    description: "Whether to download build artifacts"
    required: false
    default: "true"
  terraform-version:
    description: "Terraform version to use"
    required: false
    default: "1.12.2"
  pulumi-version:
    description: "Pulumi version to use"
    required: false
    default: "3.109.0"
  upload-artifacts:
    description: "Whether to upload build artifacts (only for build job)"
    required: false
    default: "false"
  platform:
    description: "The platform type (cdk, cdktf, cfn, pulumi, terraform)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Download build artifacts
      if: inputs.download-artifacts == 'true'
      id: download-artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
      continue-on-error: true

    - name: Set artifact status
      if: inputs.download-artifacts == 'true'
      shell: bash
      run: echo "ARTIFACTS_FOUND=${{ steps.download-artifacts.outcome == 'success' && 'true' || 'false' }}" >> $GITHUB_ENV
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "npm"

    - name: Setup Python 3.12.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.11"
        check-latest: true

    - name: Setup Terraform
      if: ${{ inputs.platform == 'cdktf' || inputs.platform == 'tf'}}
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}

    - name: Install Pulumi CLI
      if: ${{ inputs.platform == 'pulumi' }}
      uses: pulumi/actions@v5
      with:
        pulumi-version: ${{ inputs.pulumi-version }}

    - name: Install pipenv
      shell: bash
      run: |
        pip install --upgrade pip pipenv==2025.0.4
        echo "PIPENV_VENV_IN_PROJECT=1" >> $GITHUB_ENV

    - name: Cache Python virtual environment
      uses: actions/cache@v4
      with:
        path: .venv
        key: ${{ runner.os }}-python-${{ hashFiles('Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Install dependencies
      shell: bash
      run: |  
        # Node dependencies (cached by setup-node)
        npm ci
        
        # Python dependencies (cached by actions/cache)
        pipenv install --dev --ignore-pipfile

    - name: Verify environment
      shell: bash
      run: |
        echo "=== Environment Verification ==="
        echo "Node.js: $(node --version)"
        echo "Python: $(python --version)"
        echo "Pipenv: $(pipenv --version)"
        echo "Terraform: $(terraform version -json 2>/dev/null | jq -r '.terraform_version' || echo 'Not installed')"
        echo "Terraform location: $(which terraform 2>/dev/null || echo 'Not found in PATH')"
        echo "Pulumi: $(pulumi version 2>/dev/null || echo 'Not installed')"
        echo "Pulumi location: $(which pulumi 2>/dev/null || echo 'Not found in PATH')"
        echo "=============================="

    - name: Setup PATH
      shell: bash
      run: |
        # Add binaries to PATH
        [ -d "node_modules/.bin" ] && echo "${{ github.workspace }}/node_modules/.bin" >> $GITHUB_PATH
        [ -d ".venv/bin" ] && echo "${{ github.workspace }}/.venv/bin" >> $GITHUB_PATH



    - name: Upload build artifacts
      if: inputs.upload-artifacts == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        include-hidden-files: true
        path: |
          bin/
          lib/
          package*.json
          Pipfile
          Pipfile.lock
          tsconfig.json
          cdk.json
          metadata.json
          lambda/


