name: "Setup Environment"
description: "Sets up Node.js, Python and Terraform environment and restores build artifacts"
inputs:
  node-version:
    description: "Node.js version to use"
    required: true
    default: "22.17.0"
  download-artifacts:
    description: "Whether to download build artifacts"
    required: false
    default: "true"
  terraform-version:
    description: "Terraform version to use"
    required: false
    default: "1.12.2"
  pulumi-version:
    description: "Pulumi version to use"
    required: false
    default: "3.109.0"
  upload-artifacts:
    description: "Whether to upload build artifacts (only for build job)"
    required: false
    default: "false"
  platform:
    description: "The platform type (cdk, cdktf, cfn, pulumi, terraform)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Download build artifacts
      if: inputs.download-artifacts == 'true'
      id: download-artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
      continue-on-error: true

    - name: Set artifact status
      if: inputs.download-artifacts == 'true'
      shell: bash
      run: echo "ARTIFACTS_FOUND=${{ steps.download-artifacts.outcome == 'success' && 'true' || 'false' }}" >> $GITHUB_ENV
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "npm"

    - name: Setup Python 3.12.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.11"
        check-latest: true

    - name: Setup Java 17
      if: ${{ inputs.platform == 'pulumi' || inputs.platform == '' }}
      uses: actions/setup-java@v4
      with:
        distribution: 'eclipse-temurin'
        java-version: '17'

    - name: Setup Gradle
      if: ${{ inputs.platform == 'pulumi' || inputs.platform == '' }}
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-home-cache-cleanup: true

    - name: Setup Terraform
      if: ${{ inputs.platform == 'cdktf' || inputs.platform == 'tf' || inputs.platform == '' }}
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}

    - name: Install Pulumi CLI
      if: ${{ inputs.platform == 'pulumi' || inputs.platform == '' }}
      uses: pulumi/actions@v5
      with:
        pulumi-version: ${{ inputs.pulumi-version }}

    - name: Cache Python virtual environment
      uses: actions/cache@v4
      with:
        path: .venv
        key: ${{ runner.os }}-python-${{ hashFiles('Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Setup environment using script
      shell: bash
      run: ./scripts/setup.sh
      env:
        NODE_VERSION: ${{ inputs.node-version }}
        TERRAFORM_VERSION: ${{ inputs.terraform-version }}
        PULUMI_VERSION: ${{ inputs.pulumi-version }}
        DOWNLOAD_ARTIFACTS: ${{ inputs.download-artifacts }}
        UPLOAD_ARTIFACTS: ${{ inputs.upload-artifacts }}
        PLATFORM: ${{ inputs.platform }}

    - name: Upload build artifacts
      if: inputs.upload-artifacts == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        include-hidden-files: true
        path: |
          bin/
          lib/
          package*.json
          Pipfile
          Pipfile.lock
          tsconfig.json
          cdk.json
          metadata.json
          lambda/
          build.gradle
          gradle/
          gradlew
          gradlew.bat
          .gradle/
          build/


