name: "Setup Environment"
description: "Sets up environment dynamically based on platform and language with optimized caching"

inputs:
  node-version:
    default: '22.17.0'
  terraform-version:
    default: '1.12.2'
  pulumi-version:
    default: '3.109.0'
  language:
    default: ''
  platform:
    default: ''
  is-analysis:
    default: 'false'
  download-artifacts:
    description: 'Whether to download build artifacts'
    required: false
    default: 'false'
  upload-artifacts:
    description: 'Whether to upload build artifacts'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    # === Checkout ===
    - name: Checkout
      uses: actions/checkout@v4

    # === Configure pipenv venv path ===
    - name: Configure pipenv venv path
      shell: bash
      run: echo "PIPENV_VENV_IN_PROJECT=1" >> "$GITHUB_ENV"

    # === Cache CDKTF generated providers (.gen) ===
    - name: Cache CDKTF generated providers
      if: ${{ inputs.platform == 'cdktf' }}
      uses: actions/cache@v4
      with:
        path: .gen
        key: gen-${{ runner.os }}-${{ hashFiles('cdktf.json', 'package-lock.json', 'Pipfile.lock', '**/*.tf', '**/*.tf.json') }}
        restore-keys: |
          gen-${{ runner.os }}-

    # === Cache npm global tools (e.g., cdktf-cli, jest) ===
    - name: Cache global npm tools
      if: ${{ inputs.platform == 'cdktf' || inputs.platform == 'cdk' || inputs.platform == 'pulumi' }}
      uses: actions/cache@v4
      with:
        path: ~/.npm-global
        key: npm-global-${{ runner.os }}-${{ inputs.platform }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          npm-global-${{ runner.os }}-

    # === Setup Node.js ===
    - name: Setup Node.js
      if: ${{ inputs.language == 'ts' || inputs.language == 'js' || inputs.platform == 'cdk' || inputs.platform == 'cdktf' }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    # === Cache node_modules ===
    - name: Cache node_modules
      if: ${{ inputs.language == 'ts' || inputs.language == 'js' || inputs.platform == 'cdk' || inputs.platform == 'cdktf' || inputs.platform == 'pulumi' }}
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          ~/.npm
        key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          node-modules-${{ runner.os }}-

    # === Setup Python ===
    - name: Setup Python
      if: ${{ inputs.language == 'py' || inputs.platform == 'cfn' || (inputs.platform == 'pulumi' && inputs.language == 'py') }}
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.11'

    # === Cache pipenv virtualenv (only if Pipfile exists) ===
    - name: Cache pipenv virtualenv
      if: ${{ hashFiles('Pipfile') != '' }}
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('Pipfile.lock') }}
        restore-keys: |
          venv-${{ runner.os }}-

    # === Cache pip packages (only if Pipfile exists) ===
    - name: Cache pip packages
      if: ${{ hashFiles('Pipfile') != '' }}
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: pip-cache-${{ runner.os }}-${{ hashFiles('Pipfile.lock') }}
        restore-keys: |
          pip-cache-${{ runner.os }}-

    # === Prepare Go cache directory (clean before restore) ===
    - name: Prepare Go cache directory
      if: ${{ (inputs.platform == 'cdktf' || inputs.platform == 'cdk') && inputs.language == 'go' }}
      shell: bash
      run: |
        echo "🧹 Cleaning up Go cache directories to prevent tar warnings..."
        rm -rf ~/.cache/go-mod || true
        mkdir -p ~/.cache/go-mod
        rm -rf ~/go/pkg/mod || true
        mkdir -p ~/go/pkg/mod

    # === Setup Go (matches setup.sh) ===
    - name: Setup Go
      if: ${{ (inputs.platform == 'cdktf' || inputs.platform == 'cdk') && inputs.language == 'go' }}
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.12'

    # === Cache Go modules ===
    - name: Cache Go modules
      if: ${{ (inputs.platform == 'cdktf' || inputs.platform == 'cdk') && inputs.language == 'go' }}
      uses: actions/cache@v4
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-mod
        key: go-mod-cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          go-mod-cache-${{ runner.os }}-

    # === Setup Java (matches setup.sh) ===
    - name: Setup Java
      if: ${{ inputs.language == 'java' }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # === Setup Terraform ===
    - name: Setup Terraform
      if: ${{ inputs.platform == 'cdktf' || inputs.platform == 'tf' }}
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}

    # === Cache Terraform providers ===
    - name: Cache Terraform providers
      if: ${{ inputs.platform == 'tf' || (inputs.platform == 'cdktf' && inputs.language == 'go') }}
      uses: actions/cache@v4
      with:
        path: |
          ~/.terraform.d/plugin-cache
          lib/.terraform
        key: terraform-${{ runner.os }}-${{ hashFiles('**/*.tf', '**/*.lock.hcl') }}
        restore-keys: |
          terraform-${{ runner.os }}-

    # === Setup Pulumi ===
    - name: Setup Pulumi
      if: ${{ inputs.platform == 'pulumi' }}
      uses: pulumi/actions@v5
      with:
        pulumi-version: ${{ inputs.pulumi-version }}

    # === Execute setup.sh ===
    - name: Setup dependencies
      shell: bash
      run: ./scripts/setup.sh
      env:
        PLATFORM: ${{ inputs.platform }}
        LANGUAGE: ${{ inputs.language }}
