name: "Setup Environment"
description: "Sets up Node.js, Python and Terraform environment and restores build artifacts"
inputs:
  node-version:
    description: "Node.js version to use"
    required: true
    default: "22.17.0"
  download-artifacts:
    description: "Whether to download build artifacts"
    required: false
    default: "true"
  language:
    description: "Project language (ts, py, go, yaml, json, hcl)"
    required: false
    default: ''
  terraform-version:
    description: "Terraform version to use"
    required: false
    default: "1.12.2"
  pulumi-version:
    description: "Pulumi version to use"
    required: false
    default: "3.109.0"
  upload-artifacts:
    description: "Whether to upload build artifacts (only for build job)"
    required: false
    default: "false"
  platform:
    description: "The platform type (cdk, cdktf, cfn, pulumi, terraform)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Download build artifacts
      if: inputs.download-artifacts == 'true'
      id: download-artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
      continue-on-error: true

    - name: Set artifact status
      if: inputs.download-artifacts == 'true'
      shell: bash
      run: echo "ARTIFACTS_FOUND=${{ steps.download-artifacts.outcome == 'success' && 'true' || 'false' }}" >> $GITHUB_ENV

    - name: Setup Go cache environment for downloaded artifacts
      if: ${{ inputs.download-artifacts == 'true' && ((inputs.platform == 'cdktf' && inputs.language == 'go') || (inputs.platform == 'cdk' && inputs.language == 'go')) }}
      shell: bash
      run: |
        echo "🔧 Setting up Go cache environment variables..."
        # Expand tilde to actual home directory path
        HOME_DIR=$(echo ~)
        echo "GOCACHE=${HOME_DIR}/.cache/go-build" >> $GITHUB_ENV
        echo "GOMODCACHE=${HOME_DIR}/go/pkg/mod" >> $GITHUB_ENV
        echo "GO111MODULE=on" >> $GITHUB_ENV
        echo "✅ Go cache environment configured with home: ${HOME_DIR}"

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "npm"

    - name: Setup Python 3.12.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.11"
        check-latest: true

    - name: Setup Go 1.23.x
      if: ${{ (inputs.platform == 'cdktf' && inputs.language == 'go') || (inputs.platform == 'cdk' && inputs.language == 'go') }}
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.12'
        cache: false

    - name: Setup Java 17
      if: ${{ inputs.platform == 'pulumi' || inputs.platform == '' }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Gradle
      if: ${{ inputs.platform == 'pulumi' || inputs.platform == '' }}
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-home-cache-cleanup: true


    - name: Setup Terraform
      if: ${{ inputs.platform == 'cdktf' || inputs.platform == 'tf' || inputs.platform == '' }}
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}

    - name: Install Pulumi CLI
      if: ${{ inputs.platform == 'pulumi' || inputs.platform == '' }}
      uses: pulumi/actions@v5
      with:
        pulumi-version: ${{ inputs.pulumi-version }}

    - name: Cache Python virtual environment
      uses: actions/cache@v4
      with:
        path: .venv
        key: ${{ runner.os }}-python-${{ hashFiles('Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Download Go dependencies (Build stage only)
      if: ${{ inputs.upload-artifacts == 'true' && ((inputs.platform == 'cdktf' && inputs.language == 'go') || (inputs.platform == 'cdk' && inputs.language == 'go')) }}
      shell: bash
      run: |
        echo "🔧 Downloading ALL Go dependencies for all pipeline stages..."
        # Expand tilde to actual home directory path
        HOME_DIR=$(echo ~)
        export GOCACHE="${HOME_DIR}/.cache/go-build"
        export GOMODCACHE="${HOME_DIR}/go/pkg/mod"
        export GO111MODULE=on
        echo "Using GOCACHE: ${GOCACHE}"
        echo "Using GOMODCACHE: ${GOMODCACHE}"
        
        # Create cache directories if they don't exist
        mkdir -p "${GOCACHE}" "${GOMODCACHE}"
        
        # Download base dependencies
        echo "📦 Downloading base module dependencies..."
        go mod download
        go mod tidy
        
        # Pre-download test dependencies by running test in download-only mode
        echo "📦 Pre-downloading test dependencies..."
        go test -i ./... 2>/dev/null || true
        go list -test -deps ./... | xargs go get -d 2>/dev/null || true
        
        # Pre-download build dependencies
        echo "📦 Pre-downloading build dependencies..."
        go build -i ./... 2>/dev/null || true
        
        # Download lint tool dependencies
        echo "📦 Pre-downloading lint tool dependencies..."
        go get -d golang.org/x/tools/cmd/gofmt 2>/dev/null || true
        go get -d golang.org/x/lint/golint 2>/dev/null || true
        
        # Ensure all transitive dependencies are downloaded
        echo "📦 Ensuring all transitive dependencies are cached..."
        go mod download all
        
        # Warm up the build cache
        echo "📦 Warming up build cache..."
        go build -a ./... 2>/dev/null || true
        
        # Verify cache contents
        echo "📊 Verifying cache contents..."
        echo "Module cache size: $(du -sh "${GOMODCACHE}" 2>/dev/null | cut -f1 || echo 'N/A')"
        echo "Build cache size: $(du -sh "${GOCACHE}" 2>/dev/null | cut -f1 || echo 'N/A')"
        echo "Cached modules: $(find "${GOMODCACHE}" -name "*.mod" 2>/dev/null | wc -l || echo '0') modules"
        
        echo "✅ All Go dependencies downloaded and build cache warmed up"

    - name: Setup environment using script
      shell: bash
      run: ./scripts/setup.sh
      env:
        NODE_VERSION: ${{ inputs.node-version }}
        TERRAFORM_VERSION: ${{ inputs.terraform-version }}
        PULUMI_VERSION: ${{ inputs.pulumi-version }}
        DOWNLOAD_ARTIFACTS: ${{ inputs.download-artifacts }}
        UPLOAD_ARTIFACTS: ${{ inputs.upload-artifacts }}
        PLATFORM: ${{ inputs.platform }}
        LANGUAGE: ${{ inputs.language }}

    - name: Upload build artifacts
      if: inputs.upload-artifacts == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        include-hidden-files: true
        path: |
          bin/
          lib/
          tests/
          src/
          package*.json
          Pipfile
          Pipfile.lock
          tsconfig.json
          cdk.json
          metadata.json
          lambda/
          build.gradle
          settings.gradle
          gradle.properties
          gradle/
          gradlew
          gradlew.bat
          config/
          .gradle/
          build/
          go.mod
          go.sum
          tap.go
          ~/.cache/go-build
          ~/go/pkg/mod
