name: "Setup Environment"
description: "Sets up environment dynamically based on platform and language"

inputs:
  node-version:
    default: '22.17.0'
  terraform-version:
    default: '1.12.2'
  pulumi-version:
    default: '3.109.0'
  language:
    default: ''
  platform:
    default: ''
  is-analysis:
    default: 'false'
  download-artifacts:
    description: 'Whether to download build artifacts'
    required: false
    default: 'false'
  upload-artifacts:
    description: 'Whether to upload build artifacts'
    required: false
    default: 'false'


runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Node (only if needed)
    - name: Setup Node.js
      if: ${{ inputs.language == 'ts' || inputs.language == 'js' || inputs.platform == 'cdk' || inputs.platform == 'cdktf' }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    # Python (only if used)
    - name: Setup Python
      if: ${{ inputs.language == 'py' || (inputs.platform == 'pulumi' && inputs.language == 'py') }}
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.11'

    # Go
    - name: Setup Go
      if: ${{ (inputs.platform == 'cdktf' || inputs.platform == 'cdk') && inputs.language == 'go' }}
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.12'

    # Java
    - name: Setup Java
      if: ${{ inputs.language == 'java' }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # Terraform
    - name: Setup Terraform
      if: ${{ inputs.platform == 'cdktf' || inputs.platform == 'tf' }}
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}

    # Pulumi
    - name: Setup Pulumi
      if: ${{ inputs.platform == 'pulumi' }}
      uses: pulumi/actions@v5
      with:
        pulumi-version: ${{ inputs.pulumi-version }}

    # Execute script (setup.sh handles dependency installation)
    - name: Setup dependencies
      shell: bash
      run: ./scripts/setup.sh
      env:
        PLATFORM: ${{ inputs.platform }}
        LANGUAGE: ${{ inputs.language }}
