name: "Setup Environment"
description: "Sets up environment dynamically based on platform and language"

inputs:
  node-version:
    default: '22.17.0'
  terraform-version:
    default: '1.12.2'
  pulumi-version:
    default: '3.109.0'
  language:
    default: ''
  platform:
    default: ''
  is-analysis:
    default: 'false'
  download-artifacts:
    description: 'Whether to download build artifacts'
    required: false
    default: 'false'
  upload-artifacts:
    description: 'Whether to upload build artifacts'
    required: false
    default: 'false'



runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    # ✅ Restore NPM Cache (only if JS/TS/CDK/CDKTF/Pulumi TS)
    - name: Cache CDKTF generated providers
      if: ${{ inputs.platform == 'cdktf' }}
      uses: actions/cache@v4
      with:
        path: .gen
        key: gen-${{ runner.os }}-${{ hashFiles('cdktf.json') }}
        restore-keys: |
          gen-${{ runner.os }}-
    - name: Cache pipenv virtualenv
      if: ${{ inputs.language == 'py' }}
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('Pipfile.lock') }}
        restore-keys: |
          venv-${{ runner.os }}-
    - name: Cache npm packages
      if: ${{ inputs.language == 'ts' || inputs.language == 'js' || inputs.platform == 'cdk' || inputs.platform == 'cdktf' || inputs.platform == 'pulumi' }}
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: npm-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          npm-cache-${{ runner.os }}-

    # ✅ Restore pip cache (only if Python)
    - name: Cache pip packages
      if: ${{ inputs.language == 'py' }}
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: pip-cache-${{ runner.os }}-${{ hashFiles('Pipfile.lock') }}
        restore-keys: |
          pip-cache-${{ runner.os }}-

    # ✅ Restore Go build/module cache (only if Go)
    - name: Cache Go modules
      if: ${{ inputs.language == 'go' }}
      uses: actions/cache@v4
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: go-mod-cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          go-mod-cache-${{ runner.os }}-
    # Node (only if needed)
    - name: Setup Node.js
      if: ${{ inputs.language == 'ts' || inputs.language == 'js' || inputs.platform == 'cdk' || inputs.platform == 'cdktf' }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    # Python (only if used)
    - name: Setup Python
      if: ${{ inputs.language == 'py' || (inputs.platform == 'pulumi' && inputs.language == 'py') }}
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.11'

    # Go
    - name: Setup Go
      if: ${{ (inputs.platform == 'cdktf' || inputs.platform == 'cdk') && inputs.language == 'go' }}
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.12'

    # Java
    - name: Setup Java
      if: ${{ inputs.language == 'java' }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # Terraform
    - name: Setup Terraform
      if: ${{ inputs.platform == 'cdktf' || inputs.platform == 'tf' }}
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}

    # Pulumi
    - name: Setup Pulumi
      if: ${{ inputs.platform == 'pulumi' }}
      uses: pulumi/actions@v5
      with:
        pulumi-version: ${{ inputs.pulumi-version }}

    # Execute script (setup.sh handles dependency installation)
    - name: Setup dependencies
      shell: bash
      run: ./scripts/setup.sh
      env:
        PLATFORM: ${{ inputs.platform }}
        LANGUAGE: ${{ inputs.language }}
