"""Integration tests for TapStack CDK stack.

This module contains integration tests that verify the CloudFormation template
generated by the TapStack CDK stack meets all security and functional requirements.
"""

import json
import pytest
from aws_cdk import App, Stack
from aws_cdk.assertions import Template, Match

from lib.tap_stack import TapStack, TapStackProps


class TestTapStackIntegration:
  """Integration tests for TapStack CDK stack."""

  @pytest.fixture
  def app(self):
    """Create a CDK app instance for testing."""
    return App()

  @pytest.fixture
  def stack(self, app):
    """Create a TapStack instance for testing."""
    return TapStack(
      app,
      "TestTapStack",
      props=TapStackProps(
        environment_suffix="test",
        principal_arns=["arn:aws:iam::123456789012:user/test-user"]
      )
    )

  @pytest.fixture
  def template(self, stack):
    """Generate CloudFormation template from the stack."""
    return Template.from_stack(stack)

  def test_kms_key_created(self, template):
    """Test that a single KMS key resource is created."""
    template.has_resource_properties(
      "AWS::KMS::Key",
      {
        "EnableKeyRotation": True,
        "KeyPolicy": Match.any_value()
      }
    )

    # Verify only one KMS key is created
    template.resource_count_is("AWS::KMS::Key", 1)

  def test_s3_bucket_created(self, template):
    """Test that a single S3 bucket resource is created."""
    template.has_resource_properties(
      "AWS::S3::Bucket",
      {
        "BucketName": "secure-test-data-bucket-1",
        "VersioningConfiguration": {
          "Status": "Enabled"
        },
        "PublicAccessBlockConfiguration": {
          "BlockPublicAcls": True,
          "BlockPublicPolicy": True,
          "IgnorePublicAcls": True,
          "RestrictPublicBuckets": True
        }
      }
    )

    # Verify only one S3 bucket is created
    template.resource_count_is("AWS::S3::Bucket", 1)

  def test_bucket_encryption_is_kms(self, template):
    """Test that S3 bucket uses KMS encryption."""
    template.has_resource_properties(
      "AWS::S3::Bucket",
      {
        "BucketEncryption": {
          "ServerSideEncryptionConfiguration": [
            {
              "ServerSideEncryptionByDefault": {
                "SSEAlgorithm": "aws:kms"
              }
            }
          ]
        }
      }
    )

  def test_bucket_policy_exists(self, template):
    """Test that bucket policy resource exists."""
    template.has_resource_properties(
      "AWS::S3::BucketPolicy",
      {
        "PolicyDocument": Match.any_value()
      }
    )

    # Verify bucket policy is created
    template.resource_count_is("AWS::S3::BucketPolicy", 1)

  def test_bucket_policy_restricts_unencrypted_uploads(self, template):
    """Test that bucket policy denies unencrypted uploads."""
    template.has_resource_properties(
      "AWS::S3::BucketPolicy",
      {
        "PolicyDocument": {
          "Statement": Match.array_with([
            Match.object_like({
              "Sid": "DenyUnEncryptedObjectUploads",
              "Effect": "Deny",
              "Action": "s3:PutObject",
              "Condition": {
                "StringNotEquals": {
                  "s3:x-amz-server-side-encryption": "aws:kms"
                }
              }
            })
          ])
        }
      }
    )

  def test_stack_outputs_exist(self, template):
    """Test that required CloudFormation outputs exist."""
    template.has_output("BucketName", {})
    template.has_output("BucketArn", {})
    template.has_output("KmsKeyArn", {})

  def test_bucket_policy_has_principal_control(self, template):
    """Test that bucket policy includes principal-based access control."""
    template.has_resource_properties(
      "AWS::S3::BucketPolicy",
      {
        "PolicyDocument": {
          "Statement": Match.array_with([
            Match.object_like({
              "Action": ["s3:GetObject", "s3:PutObject", "s3:ListBucket"],
              "Principal": {
                "AWS": "arn:aws:iam::123456789012:user/test-user"
              }
            })
          ])
        }
      }
    )

  def test_bucket_policy_denies_http_access(self, template):
    """Test that bucket policy denies HTTP access (HTTPS-only)."""
    template.has_resource_properties(
      "AWS::S3::BucketPolicy",
      {
        "PolicyDocument": {
          "Statement": Match.array_with([
            Match.object_like({
              "Effect": "Deny",
              "Condition": {
                "Bool": {
                  "aws:SecureTransport": "false"
                }
              }
            })
          ])
        }
      }
    )

  def test_kms_key_policy_includes_s3_service_principal(self, template):
    """Test that KMS key policy includes S3 service principal."""
    template.has_resource_properties(
      "AWS::KMS::Key",
      {
        "KeyPolicy": {
          "Statement": Match.array_with([
            Match.object_like({
              "Principal": {
                "Service": "s3.amazonaws.com"
              },
              "Action": [
                "kms:Encrypt",
                "kms:Decrypt",
                "kms:GenerateDataKey"
              ]
            })
          ])
        }
      }
    )

  def test_kms_key_policy_includes_user_principal(self, template):
    """Test that KMS key policy includes user principal."""
    template.has_resource_properties(
      "AWS::KMS::Key",
      {
        "KeyPolicy": {
          "Statement": Match.array_with([
            Match.object_like({
              "Principal": {
                "AWS": "arn:aws:iam::123456789012:user/test-user"
              },
              "Action": [
                "kms:Encrypt",
                "kms:Decrypt",
                "kms:GenerateDataKey"
              ]
            })
          ])
        }
      }
    )

  def test_s3_bucket_has_correct_removal_policy(self, template):
    """Test that S3 bucket has correct removal policy."""
    template.has_resource_properties(
      "AWS::S3::Bucket",
      {
        "DeletionPolicy": "Destroy",
        "UpdateReplacePolicy": "Destroy"
      }
    )

  def test_kms_key_has_correct_removal_policy(self, template):
    """Test that KMS key has correct removal policy."""
    template.has_resource_properties(
      "AWS::KMS::Key",
      {
        "DeletionPolicy": "Destroy",
        "UpdateReplacePolicy": "Destroy"
      }
    )

  def test_s3_bucket_has_tags(self, template):
    """Test that S3 bucket has required tags."""
    template.has_resource_properties(
      "AWS::S3::Bucket",
      {
        "Tags": Match.array_with([
          Match.object_like({
            "Key": "Environment",
            "Value": "test"
          }),
          Match.object_like({
            "Key": "Project",
            "Value": "SecureStorage"
          })
        ])
      }
    )

  def test_kms_key_alias_exists(self, template):
    """Test that KMS key alias is created."""
    template.has_resource_properties(
      "AWS::KMS::Alias",
      {
        "AliasName": "alias/secure-s3-key-1",
        "TargetKeyId": Match.any_value()
      }
    )

  def test_nested_stack_structure(self, template):
    """Test that nested stack structure is correct."""
    # Verify that the nested stack is created
    template.has_resource("AWS::CloudFormation::Stack", {})

  def test_bucket_name_follows_naming_convention(self, template):
    """Test that bucket name follows the expected naming convention."""
    template.has_resource_properties(
      "AWS::S3::Bucket",
      {
        "BucketName": "secure-test-data-bucket-1"
      }
    )

  def test_bucket_encryption_uses_kms_key(self, template):
    """Test that bucket encryption references the KMS key."""
    template.has_resource_properties(
      "AWS::S3::Bucket",
      {
        "BucketEncryption": {
          "ServerSideEncryptionConfiguration": [
            {
              "ServerSideEncryptionByDefault": {
                "SSEAlgorithm": "aws:kms",
                "KMSMasterKeyID": Match.any_value()
              }
            }
          ]
        }
      }
    )

  def test_bucket_policy_denies_public_access(self, template):
    """Test that bucket policy denies public access."""
    template.has_resource_properties(
      "AWS::S3::BucketPolicy",
      {
        "PolicyDocument": {
          "Statement": Match.array_with([
            Match.object_like({
              "Effect": "Deny",
              "Principal": "*",
              "Action": "s3:*",
              "Condition": {
                "Bool": {
                  "aws:SecureTransport": "false"
                }
              }
            })
          ])
        }
      }
    )

  def test_stack_outputs_have_correct_values(self, stack):
    """Test that stack outputs have correct values."""
    # Get the nested stack
    nested_stack = stack.node.find_child("SecureS3Stack-test")
    
    # Verify outputs exist in the nested stack
    outputs = nested_stack.template_options.outputs
    assert "BucketName" in outputs
    assert "BucketArn" in outputs
    assert "KmsKeyArn" in outputs

  def test_environment_suffix_propagation(self, app):
    """Test that environment suffix is properly propagated."""
    # Test with different environment suffix
    stack_prod = TapStack(
      app,
      "TestTapStackProd",
      props=TapStackProps(
        environment_suffix="prod",
        principal_arns=["arn:aws:iam::123456789012:user/prod-user"]
      )
    )
    
    template_prod = Template.from_stack(stack_prod)
    template_prod.has_resource_properties(
      "AWS::S3::Bucket",
      {
        "BucketName": "secure-prod-data-bucket-1"
      }
    )

  def test_principal_arns_propagation(self, app):
    """Test that principal ARNs are properly propagated."""
    # Test with multiple principal ARNs
    stack_multi = TapStack(
      app,
      "TestTapStackMulti",
      props=TapStackProps(
        environment_suffix="multi",
        principal_arns=[
          "arn:aws:iam::123456789012:user/user1",
          "arn:aws:iam::123456789012:user/user2"
        ]
      )
    )
    
    template_multi = Template.from_stack(stack_multi)
    # Verify that bucket policy includes both principals
    template_multi.has_resource_properties(
      "AWS::S3::BucketPolicy",
      {
        "PolicyDocument": {
          "Statement": Match.array_with([
            Match.object_like({
              "Principal": {
                "AWS": "arn:aws:iam::123456789012:user/user1"
              }
            }),
            Match.object_like({
              "Principal": {
                "AWS": "arn:aws:iam::123456789012:user/user2"
              }
            })
          ])
        }
      }
    )

  def test_default_environment_suffix(self, app):
    """Test that default environment suffix is used when not provided."""
    stack_default = TapStack(
      app,
      "TestTapStackDefault",
      props=TapStackProps(
        principal_arns=["arn:aws:iam::123456789012:user/default-user"]
      )
    )
    
    template_default = Template.from_stack(stack_default)
    template_default.has_resource_properties(
      "AWS::S3::Bucket",
      {
        "BucketName": "secure-dev-data-bucket-1"
      }
    )

  def test_empty_principal_arns_handling(self, app):
    """Test that empty principal ARNs list is handled correctly."""
    stack_empty = TapStack(
      app,
      "TestTapStackEmpty",
      props=TapStackProps(
        environment_suffix="",
        principal_arns=[]
      )
    )
    
    template_empty = Template.from_stack(stack_empty)
    # Should still create the bucket and KMS key
    template_empty.has_resource_properties(
      "AWS::S3::Bucket",
      {
        "BucketName": "secure-empty-data-bucket-1"
      }
    )
    
    template_empty.has_resource_properties(
      "AWS::KMS::Key",
      {
        "EnableKeyRotation": True
      }
    )


if __name__ == "__main__":
  pytest.main([__file__])
