import fs from 'fs';
import path from 'path';

// --- Configuration ---
// Read outputs from the file generated by the CI/CD pipeline
let outputs: { [key: string]: string } = {};
try {
  const outputsPath = path.join(__dirname, '../cfn-outputs/flat-outputs.json');
  outputs = JSON.parse(fs.readFileSync(outputsPath, 'utf8'));
} catch (error) {
  // This is expected if running locally before deployment
  console.warn('Could not read cfn-outputs/flat-outputs.json. Skipping integration tests.');
}

// Dynamically get the region from the environment variable set by the CI/CD pipeline
const region = process.env.AWS_REGION || 'us-west-2';

// Conditionally run tests only if the outputs file was loaded
if (Object.keys(outputs).length > 0) {
  describe('DynamoDB Inventory System - Integration Tests', () => {
    let tableArnKey: string | undefined;
    let tableStreamArnKey: string | undefined;

    beforeAll(() => {
      // Find the output keys dynamically
      tableArnKey = Object.keys(outputs).find(key => key.endsWith('TableArn'));
      tableStreamArnKey = Object.keys(outputs).find(key => key.endsWith('TableStreamArn'));
    });

    test('should have a valid Table ARN output', () => {
      expect(tableArnKey).toBeDefined();
      const tableArn = outputs[tableArnKey!];

      // Use the dynamic region in the validation regex
      const arnRegex = new RegExp(`^arn:aws:dynamodb:${region}:\\d{12}:table\\/ProductInventory$`);
      expect(tableArn).toMatch(arnRegex);
    });

    test('should have a valid Table Stream ARN output', () => {
      expect(tableStreamArnKey).toBeDefined();
      const streamArn = outputs[tableStreamArnKey!];

      // Use the dynamic region in the validation regex
      const streamArnRegex = new RegExp(`^arn:aws:dynamodb:${region}:\\d{12}:table\\/ProductInventory\\/stream\\/\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}$`);
      expect(streamArn).toMatch(streamArnRegex);
    });
  });
} else {
  // If the outputs file is not found, run a placeholder test to indicate why the suite was skipped
  describe('DynamoDB Inventory System - Integration Tests', () => {
    test('skipping integration tests because cfn-outputs.json was not found', () => {
      expect(true).toBe(true);
    });
  });
}
