env                          = "dev"
aws_region                   = "us-east-1"
project_name                 = "weather-pipeline"
owner                        = "dev-team"
master_username              = "dbadmin"
cost_center                  = "engineering"
vpc_cidr                     = "10.0.0.0/16"
public_subnet_cidrs          = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnet_cidrs         = ["10.0.10.0/24", "10.0.11.0/24"]
stream_mode                  = "ON_DEMAND"
billing_mode                 = "PAY_PER_REQUEST"
validator_memory             = 256
analyzer_memory              = 512
alert_memory                 = 512
image_processor_memory       = 1024
training_memory              = 512
forecast_memory              = 1024
node_type                    = "cache.t3.micro"
num_cache_nodes              = 1
instance_class               = "db.t3.medium"
min_capacity                 = 0.5
max_capacity                 = 1
training_schedule_expression = "rate(12 hours)"
forecast_schedule_expression = "rate(2 hours)"
buffer_interval_s            = 300
buffer_size_mb               = 64
log_retention_days           = 7
pr_number                    = "pr7688"