{
  "tests/unit/test_tap_stack.py::TestTapStackArgs::test_tap_stack_args_both_custom_values": true,
  "tests/unit/test_tap_stack.py::TestTapStackArgs::test_tap_stack_args_custom_environment_suffix": true,
  "tests/unit/test_tap_stack.py::TestTapStackArgs::test_tap_stack_args_custom_tags": true,
  "tests/unit/test_tap_stack.py::TestTapStackArgs::test_tap_stack_args_empty_string_environment_suffix": true,
  "tests/unit/test_tap_stack.py::TestTapStack::test_availability_zones_edge_cases": true,
  "tests/unit/test_tap_stack.py::TestTapStack::test_availability_zones_two_azs_only": true,
  "tests/unit/test_tap_stack.py::TestTapStack::test_config_domain_name_none": true,
  "tests/unit/test_tap_stack.py::TestTapStack::test_find_least_vpc_region_error_handling": true,
  "tests/unit/test_tap_stack.py::TestTapStack::test_minimal_region_list": true,
  "tests/unit/test_tap_stack.py::TestTapStack::test_region_provider_creation": true,
  "tests/unit/test_tap_stack.py::TestTapStack::test_search_vpc_error_handling": true,
  "tests/unit/test_tap_stack.py::TestTapStack::test_tap_stack_component_resource_initialization": true,
  "tests/unit/test_tap_stack.py::TestTapStack::test_tap_stack_vpc_not_found_creates_new": true,
  "tests/unit/test_tap_stack.py::TestTapStack::test_tap_stack_with_domain_name": true,
  "tests/unit/test_tap_stack.py::TestTapStack::test_tap_stack_with_existing_vpc_found": true,
  "tests/unit/test_tap_stack.py::TestTapStack::test_vpc_cidr_configuration": true,
  "tests/unit/test_tap_stack.py::TestTapStack::test_vpc_region_exception_handling": true,
  "tests/unit/test_tap_stack.py::TestTapStack::test_vpc_region_search_with_multiple_regions": true,
  "tests/unit/test_tap_stack.py::TestTapStack::test_api_gateway_configuration": true,
  "tests/unit/test_tap_stack.py::TestTapStack::test_common_tags_structure": true,
  "tests/unit/test_tap_stack.py::TestTapStack::test_lambda_code_path_construction": true,
  "tests/unit/test_tap_stack.py::TestTapStack::test_lambda_function_configuration": true,
  "tests/unit/test_tap_stack.py::TestTapStack::test_stack_attributes_assignment": true,
  "tests/unit/test_tap_stack.py::TestTapStack::test_tap_stack_initialization": true
}