# Production environment variables
aws_region         = "us-east-1"
environment_suffix = "prod"
repository         = "iac-test-automations"
commit_author      = "production-deploy"
pr_number          = "prod"
team               = "4"
project_name       = "CorpApp"
vpc_cidr           = "10.0.0.0/16"
instance_type      = "t3.small"
db_instance_class  = "db.t3.small"
