resource "aws_db_subnet_group" "default" {
  name       = "db-subnet-group-${var.resource_suffix}"
  subnet_ids = [aws_subnet.private_1.id, aws_subnet.private_2.id]

  tags = {
    Name = "db-subnet-group-${var.resource_suffix}"
  }
}

resource "aws_security_group" "rds_sg" {
  name        = "rds-sg-${var.resource_suffix}"
  description = "Security group for RDS"
  vpc_id      = aws_vpc.main.id

  ingress {
    from_port       = 3306
    to_port         = 3306
    protocol        = "tcp"
    security_groups = [aws_security_group.ec2_sg.id]
    description     = "MySQL access from EC2 instances"
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
    description = "Allow all outbound traffic"
  }

  tags = {
    Name = "rds-sg-${var.resource_suffix}"
  }
}

# Generate a secure password only when none provided
resource "random_password" "db" {
  count  = var.db_password == "" ? 1 : 0
  length = 32

  # Keep character-class controls; do not use unsupported override_characters
  special = true
  upper   = true
  lower   = true
  number  = true
}

# Optionally store generated password in Secrets Manager (created only if we generated it)
resource "aws_secretsmanager_secret" "rds_password" {
  count       = var.db_password == "" ? 1 : 0
  name        = "rds-password-${var.resource_suffix}"
  description = "RDS password for ${var.resource_suffix} (generated by Terraform)"
}

resource "aws_secretsmanager_secret_version" "rds_password_version" {
  count        = var.db_password == "" ? 1 : 0
  secret_id    = aws_secretsmanager_secret.rds_password[0].id
  secret_string = jsonencode({
    password = random_password.db[0].result
  })
}

resource "aws_db_instance" "mysql" {
  allocated_storage       = 20
  storage_type            = "gp2"
  engine                  = "mysql"
  engine_version          = "8.0"
  instance_class          = var.db_instance_class
  db_name                 = var.db_name
  username                = var.db_username
  password                = var.db_password != "" ? var.db_password : random_password.db[0].result
  parameter_group_name    = "default.mysql8.0"
  db_subnet_group_name    = aws_db_subnet_group.default.name
  vpc_security_group_ids  = [aws_security_group.rds_sg.id]
  skip_final_snapshot     = true
  backup_retention_period = 7
  backup_window           = "03:00-04:00"
  maintenance_window      = "Mon:04:00-Mon:05:00"
  identifier              = "mysql-db-${var.resource_suffix}"

  tags = {
    Name = "mysql-db-${var.resource_suffix}"
  }
}