import * as fs from 'fs';
import * as path from 'path';

describe('CloudFormation Template Tests', () => {
  let template: any;

  beforeAll(() => {
    // Use the JSON version that gets generated by cfn-flip during unit tests
    const templatePath = path.join(__dirname, '../../lib/TapStack.json');
    if (fs.existsSync(templatePath)) {
      const fileContents = fs.readFileSync(templatePath, 'utf8');
      template = JSON.parse(fileContents);
    }
  });

  test('template should have AWSTemplateFormatVersion', () => {
    expect(template).toHaveProperty('AWSTemplateFormatVersion');
    expect(template.AWSTemplateFormatVersion).toBe('2010-09-09');
  });

  test('template should have Description', () => {
    expect(template).toHaveProperty('Description');
    expect(typeof template.Description).toBe('string');
  });

  test('template should have Resources', () => {
    expect(template).toHaveProperty('Resources');
    expect(typeof template.Resources).toBe('object');
    expect(Object.keys(template.Resources).length).toBeGreaterThan(0);
  });

  test('all resources should have Type property', () => {
    const resources = template.Resources || {};
    Object.keys(resources).forEach(resourceKey => {
      expect(resources[resourceKey]).toHaveProperty('Type');
      expect(typeof resources[resourceKey].Type).toBe('string');
    });
  });
});
