import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as ec2 from 'aws-cdk-lib/aws-ec2';

interface TapStackProps extends cdk.StackProps {
  environmentSuffix?: string;
}

export class TapStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: TapStackProps) {
    super(scope, id, props);

    // Get environment suffix from props, context, or use 'dev' as default
    const environmentSuffix =
      props?.environmentSuffix ||
      this.node.tryGetContext('environmentSuffix') ||
      'dev';

    const stackName = `TapStack${environmentSuffix}`;

    // Create VPC with CIDR 10.0.0.0/16
    const vpc = new ec2.Vpc(this, 'TapVpc', {
      ipAddresses: ec2.IpAddresses.cidr('10.0.0.0/16'),
      maxAzs: 2, // Use exactly 2 availability zones
      subnetConfiguration: [
        {
          cidrMask: 24,
          name: 'PublicSubnet',
          subnetType: ec2.SubnetType.PUBLIC,
        },
        {
          cidrMask: 24,
          name: 'PrivateSubnet',
          subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS,
        },
      ],
      natGateways: 1, // Deploy 1 NAT Gateway for cost optimization
      enableDnsHostnames: true,
      enableDnsSupport: true,
    });

    // Create security group for SSH access restricted to 203.0.113.0/24
    const sshSecurityGroup = new ec2.SecurityGroup(this, 'SshSecurityGroup', {
      vpc: vpc,
      description: 'Security group for SSH access from specific IP range',
      allowAllOutbound: true,
    });

    // Add SSH access rule restricted to 203.0.113.0/24
    sshSecurityGroup.addIngressRule(
      ec2.Peer.ipv4('203.0.113.0/24'),
      ec2.Port.tcp(22),
      'Allow SSH access from specific IP range 203.0.113.0/24'
    );

    // Create key pair for SSH access
    const keyPair = new ec2.CfnKeyPair(this, 'TapKeyPair', {
      keyName: `tap-key-${environmentSuffix}`,
      keyType: 'rsa',
    });

    // Create EC2 instance in public subnet
    const publicInstance = new ec2.Instance(this, 'PublicInstance', {
      vpc: vpc,
      vpcSubnets: {
        subnetType: ec2.SubnetType.PUBLIC,
      },
      instanceType: ec2.InstanceType.of(
        ec2.InstanceClass.T3,
        ec2.InstanceSize.MICRO
      ),
      machineImage: ec2.MachineImage.latestAmazonLinux2023(),
      securityGroup: sshSecurityGroup,
      instanceName: `tap-public-instance-${environmentSuffix}`,
      keyName: keyPair.keyName,
    });

    // Create EC2 instance in private subnet
    const privateInstance = new ec2.Instance(this, 'PrivateInstance', {
      vpc: vpc,
      vpcSubnets: {
        subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS,
      },
      instanceType: ec2.InstanceType.of(
        ec2.InstanceClass.T3,
        ec2.InstanceSize.MICRO
      ),
      machineImage: ec2.MachineImage.latestAmazonLinux2023(),
      securityGroup: sshSecurityGroup,
      instanceName: `tap-private-instance-${environmentSuffix}`,
      keyName: keyPair.keyName,
    });

    // Apply Environment=Development tag to all resources in the stack
    cdk.Tags.of(this).add('Environment', 'Development');

    // Output important resource information
    new cdk.CfnOutput(this, 'VpcId', {
      value: vpc.vpcId,
      description: 'VPC ID',
      exportName: `${stackName}-VpcId`,
    });

    new cdk.CfnOutput(this, 'VpcCidr', {
      value: vpc.vpcCidrBlock,
      description: 'VPC CIDR Block',
      exportName: `${stackName}-VpcCidr`,
    });

    new cdk.CfnOutput(this, 'PublicSubnetIds', {
      value: vpc.publicSubnets.map(subnet => subnet.subnetId).join(','),
      description: 'Public Subnet IDs',
      exportName: `${stackName}-PublicSubnetIds`,
    });

    new cdk.CfnOutput(this, 'PrivateSubnetIds', {
      value: vpc.privateSubnets.map(subnet => subnet.subnetId).join(','),
      description: 'Private Subnet IDs',
      exportName: `${stackName}-PrivateSubnetIds`,
    });

    // Output NAT Gateway IDs (CDK creates them automatically with PRIVATE_WITH_EGRESS subnet type)
    let natGatewayId = 'AutoGenerated';
    try {
      const natGatewayProvider = vpc.node
        .findChild('PublicSubnetSubnet1')
        .node.findChild('NATGateway') as cdk.CfnResource;
      natGatewayId = natGatewayProvider.ref;
    } catch {
      // NAT Gateway might be auto-generated by CDK
    }
    new cdk.CfnOutput(this, 'NatGatewayIds', {
      value: natGatewayId,
      description: 'NAT Gateway ID',
      exportName: `${stackName}-NatGatewayId`,
    });

    new cdk.CfnOutput(this, 'InternetGatewayId', {
      value: vpc.internetGatewayId || 'N/A',
      description: 'Internet Gateway ID',
      exportName: `${stackName}-InternetGatewayId`,
    });

    new cdk.CfnOutput(this, 'PublicInstanceId', {
      value: publicInstance.instanceId,
      description: 'Public EC2 Instance ID',
      exportName: `${stackName}-PublicInstanceId`,
    });

    new cdk.CfnOutput(this, 'PrivateInstanceId', {
      value: privateInstance.instanceId,
      description: 'Private EC2 Instance ID',
      exportName: `${stackName}-PrivateInstanceId`,
    });

    new cdk.CfnOutput(this, 'PublicInstancePublicIp', {
      value: publicInstance.instancePublicIp,
      description: 'Public EC2 Instance Public IP',
      exportName: `${stackName}-PublicInstancePublicIp`,
    });

    new cdk.CfnOutput(this, 'PublicInstancePrivateIp', {
      value: publicInstance.instancePrivateIp,
      description: 'Public EC2 Instance Private IP',
      exportName: `${stackName}-PublicInstancePrivateIp`,
    });

    new cdk.CfnOutput(this, 'PrivateInstancePrivateIp', {
      value: privateInstance.instancePrivateIp,
      description: 'Private EC2 Instance Private IP',
      exportName: `${stackName}-PrivateInstancePrivateIp`,
    });

    new cdk.CfnOutput(this, 'SecurityGroupId', {
      value: sshSecurityGroup.securityGroupId,
      description: 'SSH Security Group ID',
      exportName: `${stackName}-SecurityGroupId`,
    });

    new cdk.CfnOutput(this, 'KeyPairName', {
      value: keyPair.keyName || 'N/A',
      description: 'EC2 Key Pair Name',
      exportName: `${stackName}-KeyPairName`,
    });

    new cdk.CfnOutput(this, 'KeyPairId', {
      value: keyPair.attrKeyPairId,
      description: 'EC2 Key Pair ID',
      exportName: `${stackName}-KeyPairId`,
    });

    new cdk.CfnOutput(this, 'EnvironmentSuffix', {
      value: environmentSuffix,
      description: 'Environment Suffix',
      exportName: `${stackName}-EnvironmentSuffix`,
    });
  }
}
