import { Testing } from 'cdktf';
import { TapStack } from '../lib/tap-stack';

describe('TapStack Unit Tests', () => {
  let synthesized: any;

  beforeAll(() => {
    const app = Testing.app({ stackTraces: false });
    const stack = new TapStack(app, 'MultiAzFailureRecoveryStack');
    synthesized = JSON.parse(Testing.synth(stack));
  });

  const findResources = (type: string) => synthesized.resource[type] || {};
  const countResources = (type: string) => Object.keys(findResources(type)).length;

  it('should create one AWS provider for us-east-1', () => {
    expect(synthesized.provider.aws).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ region: 'us-east-1' }),
      ]),
    );
    expect(synthesized.provider.aws).toHaveLength(1); // Only one provider
  });

  it('should create a VPC', () => {
    expect(countResources('aws_vpc')).toBe(1);
  });

  it('should create 6 subnets (3 public, 3 private)', () => {
    expect(countResources('aws_subnet')).toBe(6);
  });

  it('should create 3 NAT Gateways (one per AZ)', () => {
    expect(countResources('aws_nat_gateway')).toBe(3);
  });

  it('should create one ALB, Listener, and Target Group', () => {
    expect(countResources('aws_lb')).toBe(1);
    expect(countResources('aws_lb_listener')).toBe(1);
    expect(countResources('aws_lb_target_group')).toBe(1);
  });

  it('should create one Launch Template and one ASG', () => {
    expect(countResources('aws_launch_template')).toBe(1);
    expect(countResources('aws_autoscaling_group')).toBe(1);
  });

  it('should configure ASG across 3 AZs/subnets', () => {
    const asg = Object.values(findResources('aws_autoscaling_group'))[0] as any;
    expect(asg.vpc_zone_identifier).toHaveLength(3);
    // Check if the health check type and grace period are set
    expect(asg.health_check_type).toBe('ELB');
    expect(asg.health_check_grace_period).toBe(300); // From config
  });

  it('should create one DynamoDB table', () => {
    expect(countResources('aws_dynamodb_table')).toBe(1);
    const table = Object.values(findResources('aws_dynamodb_table'))[0] as any;
    expect(table.attribute[0].name).toBe('stateKey');
  });

  it('should create one CloudWatch Metric Alarm', () => {
    expect(countResources('aws_cloudwatch_metric_alarm')).toBe(1);
    const alarm = Object.values(findResources('aws_cloudwatch_metric_alarm'))[0] as any;
    // Check some alarm properties based on config
    expect(alarm.threshold).toBe(2); // min_healthy_instances
    expect(alarm.evaluation_periods).toBe(3); // max_retry_attempts
    expect(alarm.metric_name).toBe('HealthyHostCount');
  });

  it('should create one Lambda Function', () => {
    expect(countResources('aws_lambda_function')).toBe(1);
    const lambda = Object.values(findResources('aws_lambda_function'))[0] as any;
    expect(lambda.handler).toBe('recovery.lambda_handler');
    expect(lambda.runtime).toBe('python3.9');
    expect(lambda.timeout).toBe(300); // recovery_timeout_seconds
    expect(lambda.environment.variables.DYNAMODB_TABLE).toBeDefined();
    expect(lambda.environment.variables.ASG_NAME).toBeDefined();
  });

  it('should create one EventBridge Rule and Target', () => {
    expect(countResources('aws_cloudwatch_event_rule')).toBe(1);
    expect(countResources('aws_cloudwatch_event_target')).toBe(1);
    // Check if rule targets the lambda and is triggered by the alarm
    const rule = Object.values(findResources('aws_cloudwatch_event_rule'))[0] as any;
    const target = Object.values(findResources('aws_cloudwatch_event_target'))[0] as any;

    // Use stringContaining because the exact reference includes unique IDs generated by cdktf
    expect(target.rule).toEqual(expect.stringContaining('${aws_cloudwatch_event_rule.event-rule'));
    expect(target.arn).toEqual(expect.stringContaining('${aws_lambda_function.recovery-lambda'));
    expect(JSON.parse(rule.event_pattern).resources[0]).toEqual(expect.stringContaining('${aws_cloudwatch_metric_alarm.unhealthy-host-alarm'));
  });

  it('should define all required outputs', () => {
    expect(synthesized.output).toHaveProperty('AlbDnsName');
    expect(synthesized.output).toHaveProperty('AsgName');
    expect(synthesized.output).toHaveProperty('DynamoDbTableName');
    expect(synthesized.output).toHaveProperty('RecoveryLambdaArn');
    expect(synthesized.output).toHaveProperty('CloudWatchAlarmName');
  });
});

